### ISSUE TITLE
您好，读取预训练模型继续训练，得分会很低

### ISSUE THREAD

**Issue by SniperTian** [young-how/DQN-based-UAV-3D_path_planer#15]
您好，载入预训练模型后，得分会很低，这是怎么回事呢？我自己从初始模型训练了10000个epoch，得分挺高的，但是我加载保存的模型继续训练（没有换训练数据），结果得分一下子暴跌，甚至还不如初始模型的得分，虽然经过50多个epoch以后基本恢复加载前的训练水平，但这样完全没办法在测试环境里应用。我直接执行您代码里的watch_UAV，也经常出现撞毁的现象

**Comment by SniperTian** [comment]
我找到问题了，eps = epsilon_annealing(i_episode, max_eps_episode, min_eps)  #计算贪心概率，这一步在断点续训的时候，i_episode归零导致贪心概率不同，改成epoch+i_episode就好了

**Comment by w4646** [comment]
> 您好，载入预训练模型后，得分会很低，这是怎么回事呢？我自己从初始模型训练了10000个epoch，得分挺高的，但是我加载保存的模型继续训练（没有换训练数据），结果得分一下子暴跌，甚至还不如初始模型的得分，虽然经过50多个epoch以后基本恢复加载前的训练水平，但这样完全没办法在测试环境里应用。我直接执行您代码里的watch_UAV，也经常出现撞毁的现象

你好，你跑通这个代码了吗？我再运行simulator.py文件的时候一直报错“Traceback (most recent call last):
  File "F:\code\route_planning\DQN_About\DQN-based-UAV-3D_path_planer\simulator.py", line 212, in <module>
    sim.StartAndTrain()
  File "F:\code\route_planning\DQN_About\DQN-based-UAV-3D_path_planer\simulator.py", line 119, in StartAndTrain
    info=self.env.run_eposide(eps_rate)   #计算机随机生成场景进行训练
AttributeError: 'NoneType' object has no attribute 'run_eposide'”。这是怎么回事呀
