### ISSUE TITLE
缺少训练的文件

### ISSUE THREAD

**Issue by shangguanyiyu** [young-how/DQN-based-UAV-3D_path_planer#23]
作者您好，缺少训练的文件呀，请问您可以补充一下嘛，感激不尽

**Comment by young-how** [comment]
运行simulator.py即可开始训练，若报错单步调试排查，可能是参数配置有问题

**Comment by Hheehongci** [comment]
(2, 'No such file or directory')
("'NoneType' object has no attribute 'name'",)
[Errno 2] No such file or directory: 'logs/score_11_20_2024(00_50_00).csv'
None
Iteration 0:   0%|          | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 254, in <module>
    sim.StartAndTrain()
  File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 142, in StartAndTrain
    info=self.env.run_eposide(eps_rate)   #计算机随机生成场景进行训练
AttributeError: 'NoneType' object has no attribute 'run_eposide'

作者大大，这是怎么回事啊

**Comment by lbboier** [comment]
> (2, 'No such file or directory') ("'NoneType' object has no attribute 'name'",) [Errno 2] No such file or directory: 'logs/score_11_20_2024(00_50_00).csv' None Iteration 0: 0%| | 0/50 [00:00<?, ?it/s] Traceback (most recent call last): File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 254, in sim.StartAndTrain() File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 142, in StartAndTrain info=self.env.run_eposide(eps_rate) #计算机随机生成场景进行训练 AttributeError: 'NoneType' object has no attribute 'run_eposide'
> 
> 作者大大，这是怎么回事啊

手动创建一个logs目录就行

**Comment by w4646** [comment]
> 运行simulator.py即可开始训练，若报错单步调试排查，可能是参数配置有问题

你好，我运行simulator.py文件之后报错“FileNotFoundError: [Errno 2] No such file or directory: 'DataBase/experience/6cad80c8-802a-4a25-83fe-11b30f59da86.html'”这个文件在哪呀

**Comment by w4646** [comment]
> (2, 'No such file or directory') ("'NoneType' object has no attribute 'name'",) [Errno 2] No such file or directory: 'logs/score_11_20_2024(00_50_00).csv' None Iteration 0: 0%| | 0/50 [00:00<?, ?it/s] Traceback (most recent call last): File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 254, in sim.StartAndTrain() File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 142, in StartAndTrain info=self.env.run_eposide(eps_rate) #计算机随机生成场景进行训练 AttributeError: 'NoneType' object has no attribute 'run_eposide'
> 
> 作者大大，这是怎么回事啊

你好，你的问题解决了吗

**Comment by w4646** [comment]
> 作者大大，我也是这个问题，按照要求配置好对应版本的包后，还需要修改什么东西吗，直接运行simulator.py 也是254行和142行报错，和楼上一样，求解答求解答 感激不尽~

你好，你的问题解决了吗
