### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by xch1176411706** [young-how/DQN-based-UAV-3D_path_planer#25]
各位大佬都是怎么跑出来的，我直接运行simulator.py文件

Traceback (most recent call last):
  File "E:\au\path_plan\DQN-based-UAV-3D_path_planer-main\simulator.py", line 254, in <module>
    sim.StartAndTrain()
  File "E:\au\path_plan\DQN-based-UAV-3D_path_planer-main\simulator.py", line 142, in StartAndTrain
    info=self.env.run_eposide(eps_rate)   #计算机随机生成场景进行训练
AttributeError: 'NoneType' object has no attribute 'run_eposide'
(2, 'No such file or directory')
("'NoneType' object has no attribute 'name'",)
[Errno 2] No such file or directory: 'logs/score_11_10_2024(14_44_19).csv'
None

进程已结束，退出代码为 1
就这样呢

**Comment by young-how** [comment]
因为运行架构有过修改，目前只有SAC对运行架构做了适配，其他算法可以通过类似的方法进行适配。下次提交后我会把这部分问题修复一下
