### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Hheehongci** [young-how/DQN-based-UAV-3D_path_planer#26]
作者大大，我换成py3.97后，也安装了所以所需环境pip install -r requirements.txt，为什么会报下面的错误啊

Iteration 0:   0%|          | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 254, in <module>
    sim.StartAndTrain()
  File "C:\Users\何必\PycharmProjects\DQN_test\DQN-based-UAV-3D_path_planer-main\simulator.py", line 142, in StartAndTrain
    info=self.env.run_eposide(eps_rate)   #计算机随机生成场景进行训练
AttributeError: 'NoneType' object has no attribute 'run_eposide'
(2, 'No such file or directory')
("'NoneType' object has no attribute 'name'",)
[Errno 2] No such file or directory: 'logs/score_11_20_2024(01_01_51).csv'
None

进程已结束，退出代码为 1

**Comment by JQWCSU** [comment]
我也是line254和line142报错，请问应该修改哪里呢

**Comment by young-how** [comment]
主目录还缺少一个logs目录，没有的话手动创建一个。

**Comment by JQWCSU** [comment]
作者大大 感谢您的回答！对我帮助很大，还有2个问题想请教您：
1.路径规划的起点和终点在哪里设置哇~（找了半天没找到）
2.直接运行simulator.py 会显示进度条，默认环境building，训练完成后，不知道在哪里查看路径规划的可视化结果，以及是否规划成功（拜托拜托~~）

**Comment by JQWCSU** [comment]
作者大大 感谢您的回答！对我帮助很大，还有2个问题想请教您：
1.路径规划的起点和终点在哪里设置哇~（找了半天没找到）
2.直接运行simulator.py 会显示进度条，默认环境building，训练完成后，不知道在哪里查看路径规划的可视化结果，以及是否规划成功（拜托拜托~~）

**Comment by JQWCSU** [comment]
作者大大，我打开我的html文件后（未更改训练模型、训练环境、相关参数），没显示障碍物，只能显示一部分路径。由于看不到起点和终点、障碍物，就不知道是否绕避成功（可能是我哪里弄错了），可以麻烦您解答一下嘛，万分感激~

**Comment by young-how** [comment]
调试模式下查看障碍物是否又被初始化生成到ENV环境类中，如果环境类中有障碍物类但是没显示，检查生成html的函数是否出问题。

**Comment by w4646** [comment]
> 作者大大 感谢您的回答！对我帮助很大，还有2个问题想请教您： 1.路径规划的起点和终点在哪里设置哇~（找了半天没找到） 2.直接运行simulator.py 会显示进度条，默认环境building，训练完成后，不知道在哪里查看路径规划的可视化结果，以及是否规划成功（拜托拜托~~）

你好，你的能跑通吗
