### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 19ssyy** [young-how/DQN-based-UAV-3D_path_planer#27]
作者大大，运行simulator.py后报如下错误
('gbk', b'<simulator>\n    <env>\n        <Env_Type>PathPlan_City</Env_Type>   \n        <len>500</len>  \n        <width>500</width>  \n        <h>100</h>  \n        <eps>0.1</eps>  \n        <Is_AC>0</Is_AC>\n        <Is_FL>0</Is_FL>   \n        <Is_On_Policy>0</Is_On_Policy>\n        <FL_Loop>3</FL_Loop>\n        <print_loop>2</print_loop>\n        <num_UAV>1</num_UAV> \n        <Agent>\n            <xml_path_agent>./config/UAV.xml</xml_path_agent>   \n            <Trainer>\n                <Trainer_path>./config/Trainer.xml</Trainer_path>  \n            </Trainer>\n        </Agent>\n        <Obstacles>\n            <buildings>./config/buildings.xml</buildings>  \n        </Obstacles>\n        <UI>\n            <UI_path>./config/UI.xml</UI_path>\n        </UI>\n        <DB>\n            <DB_path>./config/DB.xml</DB_path>  \n        </DB>\n    </env>\n    <record_epo>10</record_epo>\n    <num_episodes>500</num_episodes>   \n    <max_eps_episode>1</max_eps_episode>\n    <min_eps>0.1</min_eps>\n    <TARGET_UPDATE>3</TARGET_UPDATE>\n</simulator>', 74, 75, 'illegal multibyte sequence')
None
Iteration 0:   0%|          | 0/15000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\PythonProject\pythonProject1\DQN-based-UAV-3D_path_planer-main\simulator.py", line 234, in <module>
    sim.StartAndTrain()
  File "D:\PythonProject\pythonProject1\DQN-based-UAV-3D_path_planer-main\simulator.py", line 124, in StartAndTrain
    info = self.env.run_eposide(eps_rate)  #计算机随机生成场景进行训练
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'run_eposide'
要怎么调整修改呢？

**Comment by lixi11246** [comment]
同问，请问一下解决了吗

**Comment by young-how** [comment]
生成对象失败导致的，查看对应的配置文件是否正确读取，看报错可能是读取失败导致的

**Comment by w4646** [comment]
> 作者大大，运行simulator.py后报如下错误 ('gbk', b'\n \n <Env_Type>PathPlan_City</Env_Type> \n 500 \n 500 \n 100 \n 0.1 \n <Is_AC>0</Is_AC>\n <Is_FL>0</Is_FL> \n <Is_On_Policy>0</Is_On_Policy>\n <FL_Loop>3</FL_Loop>\n <print_loop>2</print_loop>\n <num_UAV>1</num_UAV> \n \n <xml_path_agent>./config/UAV.xml</xml_path_agent> \n \n <Trainer_path>./config/Trainer.xml</Trainer_path> \n \n \n \n ./config/buildings.xml \n \n \n <UI_path>./config/UI.xml</UI_path>\n \n \n <DB_path>./config/DB.xml</DB_path> \n \n \n <record_epo>10</record_epo>\n <num_episodes>500</num_episodes> \n <max_eps_episode>1</max_eps_episode>\n <min_eps>0.1</min_eps>\n <TARGET_UPDATE>3</TARGET_UPDATE>\n', 74, 75, 'illegal multibyte sequence') None Iteration 0: 0%| | 0/15000 [00:00<?, ?it/s] Traceback (most recent call last): File "D:\PythonProject\pythonProject1\DQN-based-UAV-3D_path_planer-main\simulator.py", line 234, in sim.StartAndTrain() File "D:\PythonProject\pythonProject1\DQN-based-UAV-3D_path_planer-main\simulator.py", line 124, in StartAndTrain info = self.env.run_eposide(eps_rate) #计算机随机生成场景进行训练 ^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'run_eposide' 要怎么调整修改呢？你好，我也遇到了这个错误，你是怎么修改的

**Comment by w4646** [comment]
> 同问，请问一下解决了吗

你好，你解决了吗
